language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "pypy"
  - "pypy3"
install:
  - pip install --upgrade pip
  - pip install .
script: nosetests
