language: python
matrix:
  include:
    - python: "2.7"
      dist: xenial
    - python: "3.6"
      dist: xenial
    - python: "3.7"
      dist: xenial
    - python: "3.8"
      dist: focal
    - python: "3.9"
      dist: focal
    - python: "3.10"
      dist: jammy
    - python: "3.11"
      dist: jammy
    - python: "nightly"
      dist: jammy
    - python: "pypy"
      dist: jammy
    - python: "pypy3"
      dist: jammy
script: setup.py test --quiet
